jobs:
  build:
    name: Build Parquet with JDK ${{ matrix.java }} and ${{ matrix.codes }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@master
    - continue-on-error: true
      name: Set up JDK8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        CI_TARGET_BRANCH: $GITHUB_HEAD_REF
      name: before_install
      run: 'bash dev/ci-before_install.sh

        '
    - continue-on-error: true
      name: install
      run: 'EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs
        -q -DforceStdout)

        export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"

        mvn install --batch-mode -P hadoop2 -DskipTests=true -Dmaven.javadoc.skip=true
        -Dsource.skip=true -Djava.version=1.8

        '
    - continue-on-error: true
      env:
        JAVA_VERSION: ${{ matrix.java }}
        TEST_CODECS: ${{ matrix.codes }}
      name: verify
      run: 'EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs
        -q -DforceStdout)

        export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"

        mvn verify --batch-mode -P hadoop2 javadoc:javadoc

        '
    strategy:
      fail-fast: false
      matrix:
        codes:
        - uncompressed,brotli
        - gzip,snappy
name: CI Hadoop 2
on:
  repository_dispatch:
    types: trigger-ga___ci-hadoop2.yml
