jobs:
  build:
    name: Build Parquet with JDK ${{ matrix.java.setup }} and ${{ matrix.codes }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@master
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java.setup }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java.setup }}
    - continue-on-error: true
      env:
        CI_TARGET_BRANCH: $GITHUB_HEAD_REF
      name: before_install
      run: 'bash dev/ci-before_install.sh

        '
    - continue-on-error: true
      name: install
      run: 'EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs
        -q -DforceStdout)

        export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"

        mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true
        -Djava.version=${{ matrix.java.maven }}

        '
    - continue-on-error: true
      env:
        JAVA_VERSION: ${{ matrix.java.setup }}
        TEST_CODECS: ${{ matrix.codes }}
      name: verify
      run: 'EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs
        -q -DforceStdout)

        export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"

        mvn verify --batch-mode javadoc:javadoc

        '
    strategy:
      fail-fast: false
      matrix:
        codes:
        - uncompressed,brotli
        - gzip,snappy
        java:
        - maven: '1.8'
          setup: '8'
        - maven: '11'
          setup: '11'
        - maven: '17'
          setup: '17'
name: CI Hadoop 3
on:
  repository_dispatch:
    types: trigger-ga___ci-hadoop3.yml
